---
title: "Check for unexpected taxa"
date: "11/9/2017"
output: github_document
---

```{r,message=FALSE}
#chunk options
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)

#libraries
library(knitr) #r markdown
library(readr) #read/write
library(magrittr) #data formatting
library(tidyr) #data formatting
library(dplyr) #data formatting
library(ggplot2) #plotting

#fxns
HowManyOfThese<-function(otuIDs, taxAndFunguild, comm.otu){
  
  #subset the OTU table
  curr.mat.otu<-comm.otu[,colnames(comm.otu) %in% otuIDs]
  
  #get rid of cols and rows without reads
  tmp<-curr.mat.otu[,colSums(curr.mat.otu)!=0] 
  curr.mat.otu.sel<-tmp[rowSums(tmp)!=0,]
  
  #save the mini OTU table and taxon look up table
  results<-list(otu=curr.mat.otu.sel,
                tax=taxAndFunguild[taxAndFunguild$OTUId %in% colnames(curr.mat.otu.sel),c("OTUId","phylum","genus","species")])
  
  return(results)
}

```

## LOAD DATA 

### MICROBIAL COMMUNITY DATA
```{r, echo=FALSE}

#OTU table
comm.otu<-read.csv("derived_data/comm_otu.csv", row.names=1)

#taxon lookup info
taxAndFunguild<-read.csv("derived_data/taxaAndFunguild.csv")

```


Check the OTU table for unexpected taxa....  

- Arbuscular mycorrhizal fungi
```{r, echo=FALSE}
GlomOTUs<-taxAndFunguild[taxAndFunguild$phylum=="Glomeromycota","OTUId"]
HowManyOfThese(otuIDs=GlomOTUs, taxAndFunguild, comm.otu)
#am.otus<-taxAndFunguild[taxAndFunguild$Guild=="Arbuscular Mycorrhizal","OTUId"] #same as above
#HowManyOfThese(otuIDs=am.otus, taxAndFunguild, comm.otu)
```
- Ericoid mycorrhizal fungi
```{r, echo=FALSE}
ericoid.otus<-taxAndFunguild[taxAndFunguild$Guild=="Ericoid Mycorrhizal","OTUId"]
HowManyOfThese(otuIDs=ericoid.otus, taxAndFunguild, comm.otu)

#.. orchidmyc.otus<-taxAndFunguild[taxAndFunguild$Guild=="Orchid Mycorrhizal","OTUId"]
#HowManyOfThese(otuIDs=orchidmyc.otus, taxAndFunguild, comm.otu) #none
```
- Animal-associated fungi
```{r, echo=FALSE}
animal.otus<-taxAndFunguild[grepl('Animal', taxAndFunguild$Guild),"OTUId"]
tmp<-HowManyOfThese(otuIDs=animal.otus, taxAndFunguild, comm.otu)
paste(dim(tmp$tax)[1], "OTUs")
```
